services:
  arosaje-front:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "8080"

    restart: unless-stopped
    labels:
      - autoheal=true
    depends_on:
      - arosaje
    command: "npm start"
networks:
  default:
    external: true
    name: IssouNetwork_Services
